name: Node.js CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        python-version: [ 'pypy-3.8' ]

    steps:
 
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64'
    - run: python -m pip install --upgrade pip
    - run: pip install flask pymongo requests bcrypt gevent WSGIServer qrcode libscrc uvicorn fastapi coverage
    - name: echo workspace
      run: echo $GITHUB_WORKSPACE
      shell: bash
    - name: Run tests
      run: coverage run test_ci.py
    - name: Tests report
      run: coverage report
      
Continuous Deploy :
      
      run-on : windows-latest
      
      steps:
      - name : CI success
        run : echo " Countinuous Deployment is Strating "
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh deploy.sh
 
 
  
  
 



















